apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  namespace: loki
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.7.206
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 1514
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 1514
      protocol: TCP
