{{- if .Values.cloudflare.apiToken }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{ .Values.letsencrypt.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - selector:
          dnsZones:
            {{- range .Values.dnsZones }}
            - {{ . | quote }}
            {{- end }}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
{{- end }}
