apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  namespace: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-webui
  template:
    metadata:
      labels:
        app: garage-webui
    spec:
      containers:
        - name: garage-webui
          image: khairul169/garage-webui:latest
          ports:
            - containerPort: 3909
          env:
            - name: API_BASE_URL
              value: "http://garage-admin:3903"
            - name: API_ADMIN_KEY
              value: "ceb3f9d7fe6f03d6af1080211b3c074026bf0a3b284133592fd026518fd0fe3b"
            - name: S3_ENDPOINT_URL
              value: "http://garage:3900"
            - name: S3_REGION
              value: "garage"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: garage-webui
  namespace: garage
spec:
  selector:
    app: garage-webui
  ports:
    - port: 3909
      targetPort: 3909
