apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage
  namespace: garage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`garage.golden.wales`)
      kind: Rule
      middlewares:
        - name: authentik
          namespace: traefik
      services:
        - name: garage-webui
          port: 3909
  tls: {}
