apiVersion: v1
kind: Secret
metadata:
  name: homarr-oidc
  namespace: homarr
type: Opaque
stringData:
  oidc-client-id: {{ .Values.homarr.oidc.clientId | quote }}
  oidc-client-secret: {{ .Values.homarr.oidc.clientSecret | quote }}
