# Rclone credentials for media storage (Garage S3 backend)
apiVersion: v1
kind: Secret
metadata:
  name: rclone-media-secret
  namespace: media
type: Opaque
stringData:
  remote: "garage"
  remotePath: "media"
  configData: |
    [garage]
    type = s3
    provider = Other
    access_key_id = {{ .Values.rclone.accessKeyId }}
    secret_access_key = {{ .Values.rclone.secretAccessKey }}
    endpoint = {{ .Values.rclone.endpoint }}
    region = garage
    force_path_style = true
