{{- if .Values.cloudflare.apiToken }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: golden-wales-wildcard
  namespace: traefik
spec:
  secretName: golden-wales-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "golden.wales"
    - "*.golden.wales"
{{- end }}
