apiVersion: v2
name: prowlarr
description: Prowlarr indexer manager
type: application
version: 1.0.0
appVersion: "latest"
dependencies:
  - name: common
    version: 4.5.2
    repository: file://../common
