apiVersion: v2
name: cloudflared
description: Cloudflare Tunnel for exposing services
type: application
version: 0.1.0
appVersion: "2024.12.0"
dependencies:
  - name: common
    version: 4.5.2
    repository: file://../common
