{{- if .Values.tunnel.token }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: {{ .Values.tunnel.token | quote }}
{{- end }}
