apiVersion: v2
name: bazarr
description: Bazarr subtitle manager
type: application
version: 1.0.0
appVersion: "latest"
dependencies:
  - name: common
    version: 4.5.2
    repository: file://../common
