apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: mqtt
      port: {{ .Values.mqtt.port }}
      targetPort: mqtt
    - name: websocket
      port: {{ .Values.websocket.port }}
      targetPort: websocket
  selector:
    app: {{ .Release.Name }}
