---
- name: Update Cache And Install Nomad packages
  apt:
    pkg:
      - nomad
      - consul
    state: latest
  tags:
    install-nomad
    install-package
  when: nomad_node | bool

- name: Start nomad
  ansible.builtin.systemd:
    name: nomad
    state: started
  when: nomad_node | bool
  tags:
    install-nomad
    install-package
#


#- name: Force reinstall package using apt-get
#  ansible.builtin.command:
#    cmd: apt-get install --reinstall nomad
#  become: yes
#  when: legacy_node == 'false'
