apiVersion: v2
name: postgres
description: PostgreSQL database server
type: application
version: 0.1.0
appVersion: "16"
dependencies:
  - name: common
    version: 4.5.2
    repository: file://../common
